# Generated by Django 2.0.2 on 2018-03-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapeEntries', '0003_auto_20180305_0257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-createdDate']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='createDate',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
