# Generated by Django 2.0.2 on 2018-03-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapeEntries', '0009_auto_20180309_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterField(
            model_name='post',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
