# Generated by Django 2.0.2 on 2018-03-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapeEntries', '0010_auto_20180309_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['createdDate']},
        ),
    ]
